// Code generated by moshi-java-codegen. Do not edit.
package io.github.nename0.moshi.java.codegen.model.complex;

import com.squareup.moshi.JsonAdapter;
import com.squareup.moshi.JsonReader;
import com.squareup.moshi.JsonWriter;
import com.squareup.moshi.Moshi;
import com.squareup.moshi.Types;
import java.io.IOException;
import java.lang.IllegalArgumentException;
import java.lang.Override;
import java.lang.SuppressWarnings;
import java.lang.reflect.Type;
import java.util.Collections;
import java.util.List;

@SuppressWarnings("unused")
public final class GenericListFieldJsonAdapter<T> extends JsonAdapter<GenericListField<T>> {
  private static final JsonReader.Options OPTIONS = JsonReader.Options.of("list");

  private final JsonAdapter<List<T>> adapter_list;

  public GenericListFieldJsonAdapter(Moshi moshi, Type[] types) {
    if (types.length != 1) {
      throw new IllegalArgumentException("TypeVariable mismatch: Expecting 1 type(s) for generic type variables [T], but received " + types.length);
    }
    adapter_list = moshi.adapter(Types.newParameterizedType(List.class, types[0]),
        Collections.emptySet(), "list");
  }

  @Override
  public GenericListField<T> fromJson(JsonReader reader) throws IOException {
    GenericListField<T> instance = new GenericListField<T>();
    reader.beginObject();
    while (reader.hasNext()) {
      int index = reader.selectName(OPTIONS);
      switch (index) {
        case -1:
          reader.skipName();
          reader.skipValue();
          break;
        case 0:
          ((GenericListField<T>)instance).list = adapter_list.fromJson(reader);
          break;
      }
    }
    reader.endObject();
    return instance;
  }

  @Override
  public void toJson(JsonWriter writer, GenericListField<T> value) throws IOException {
    writer.beginObject();
    writer.name("list");
    adapter_list.toJson(writer, ((GenericListField<T>)value).list);
    writer.endObject();
  }
}
