// Code generated by moshi-java-codegen. Do not edit.
package io.github.nename0.moshi.java.codegen.model.simple;

import com.squareup.moshi.JsonAdapter;
import com.squareup.moshi.JsonReader;
import com.squareup.moshi.JsonWriter;
import com.squareup.moshi.Moshi;
import java.io.IOException;
import java.lang.Override;
import java.lang.SuppressWarnings;

@SuppressWarnings("unused")
public final class EmptyJsonAdapter extends JsonAdapter<Empty> {
  private static final JsonReader.Options OPTIONS = JsonReader.Options.of();

  public EmptyJsonAdapter(Moshi moshi) {
  }

  @Override
  public Empty fromJson(JsonReader reader) throws IOException {
    Empty instance = new Empty();
    reader.beginObject();
    while (reader.hasNext()) {
      int index = reader.selectName(OPTIONS);
      switch (index) {
        case -1:
          reader.skipName();
          reader.skipValue();
          break;
      }
    }
    reader.endObject();
    return instance;
  }

  @Override
  public void toJson(JsonWriter writer, Empty value) throws IOException {
    writer.beginObject();
    writer.endObject();
  }
}
