// Code generated by moshi-java-codegen. Do not edit.
package io.github.nename0.moshi.java.codegen.model.simple;

import com.squareup.moshi.JsonAdapter;
import com.squareup.moshi.JsonReader;
import com.squareup.moshi.JsonWriter;
import com.squareup.moshi.Moshi;
import java.io.IOException;
import java.lang.Override;
import java.lang.SuppressWarnings;
import java.util.Collections;

@SuppressWarnings("unused")
public final class ObjectFieldJsonAdapter extends JsonAdapter<ObjectField> {
  private static final JsonReader.Options OPTIONS = JsonReader.Options.of("object");

  private final JsonAdapter<ChildInt> adapter_object;

  public ObjectFieldJsonAdapter(Moshi moshi) {
    adapter_object = moshi.adapter(ChildInt.class, Collections.emptySet(), "object");
  }

  @Override
  public ObjectField fromJson(JsonReader reader) throws IOException {
    ObjectField instance = new ObjectField();
    reader.beginObject();
    while (reader.hasNext()) {
      int index = reader.selectName(OPTIONS);
      switch (index) {
        case -1:
          reader.skipName();
          reader.skipValue();
          break;
        case 0:
          ((ObjectField)instance).object = adapter_object.fromJson(reader);
          break;
      }
    }
    reader.endObject();
    return instance;
  }

  @Override
  public void toJson(JsonWriter writer, ObjectField value) throws IOException {
    writer.beginObject();
    writer.name("object");
    adapter_object.toJson(writer, ((ObjectField)value).object);
    writer.endObject();
  }
}
