// Code generated by moshi-java-codegen. Do not edit.
package com.github.nename0.moshi.java.codegen.model.complex;

import com.squareup.moshi.JsonAdapter;
import com.squareup.moshi.JsonReader;
import com.squareup.moshi.JsonWriter;
import com.squareup.moshi.Moshi;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Collections;

@SuppressWarnings("unused")
public final class ShadowedGetterChildJsonAdapter extends JsonAdapter<ShadowedGetterChild> {
  private static final JsonReader.Options OPTIONS = JsonReader.Options.of("id", "renamed-id");

  private final JsonAdapter<String> adapter_id_Idded;

  private final JsonAdapter<Integer> adapter_id_ShadowedGetterParent;

  public ShadowedGetterChildJsonAdapter(Moshi moshi) {
    adapter_id_Idded = moshi.adapter(String.class, Collections.emptySet(), "id");
    adapter_id_ShadowedGetterParent = moshi.adapter(int.class, Collections.emptySet(),
        "renamed-id");
  }

  @Override
  public ShadowedGetterChild fromJson(JsonReader reader) throws IOException {
    ShadowedGetterChild instance = new ShadowedGetterChild();
    reader.beginObject();
    while (reader.hasNext()) {
      int index = reader.selectName(OPTIONS);
      switch (index) {
        case -1:
          reader.skipName();
          reader.skipValue();
          break;
        case 0:
          ((GenericMiddleGetter<String>)instance).setId(adapter_id_Idded.fromJson(reader));
          break;
        case 1:
          ((ShadowedGetterChild)instance).setId(adapter_id_ShadowedGetterParent.fromJson(reader));
          break;
      }
    }
    reader.endObject();
    return instance;
  }

  @Override
  public void toJson(JsonWriter writer, ShadowedGetterChild value) throws IOException {
    writer.beginObject();
    writer.name("id");
    adapter_id_Idded.toJson(writer, ((GenericMiddleGetter<String>)value).getId());
    writer.name("renamed-id");
    adapter_id_ShadowedGetterParent.toJson(writer, ((ShadowedGetterChild)value).getid());
    writer.endObject();
  }
}
