// Code generated by moshi-java-codegen. Do not edit.
package com.github.nename0.moshi.java.codegen.model.simple;

import com.squareup.moshi.JsonAdapter;
import com.squareup.moshi.JsonReader;
import com.squareup.moshi.JsonWriter;
import com.squareup.moshi.Moshi;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Collections;

@SuppressWarnings("unused")
public final class ChildIntJsonAdapter extends JsonAdapter<ChildInt> {
  private static final JsonReader.Options OPTIONS = JsonReader.Options.of("age", "name");

  private final JsonAdapter<Integer> adapter_age;

  private final JsonAdapter<String> adapter_name;

  public ChildIntJsonAdapter(Moshi moshi) {
    adapter_age = moshi.adapter(int.class, Collections.emptySet(), "age");
    adapter_name = moshi.adapter(String.class, Collections.emptySet(), "name");
  }

  @Override
  public ChildInt fromJson(JsonReader reader) throws IOException {
    ChildInt instance = new ChildInt();
    reader.beginObject();
    while (reader.hasNext()) {
      int index = reader.selectName(OPTIONS);
      switch (index) {
        case -1:
          reader.skipName();
          reader.skipValue();
          break;
        case 0:
          ((ChildInt)instance).age = adapter_age.fromJson(reader);
          break;
        case 1:
          ((ParentString)instance).name = adapter_name.fromJson(reader);
          break;
      }
    }
    reader.endObject();
    return instance;
  }

  @Override
  public void toJson(JsonWriter writer, ChildInt value) throws IOException {
    writer.beginObject();
    writer.name("age");
    adapter_age.toJson(writer, ((ChildInt)value).age);
    writer.name("name");
    adapter_name.toJson(writer, ((ParentString)value).name);
    writer.endObject();
  }
}
