// Code generated by moshi-java-codegen. Do not edit.
package com.github.nename0.moshi.java.codegen.model.simple;

import com.squareup.moshi.JsonAdapter;
import com.squareup.moshi.JsonReader;
import com.squareup.moshi.JsonWriter;
import com.squareup.moshi.Moshi;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Collections;

@SuppressWarnings("unused")
public final class ChildEmptyJsonAdapter extends JsonAdapter<ChildEmpty> {
  private static final JsonReader.Options OPTIONS = JsonReader.Options.of("name");

  private final JsonAdapter<String> adapter_name;

  public ChildEmptyJsonAdapter(Moshi moshi) {
    adapter_name = moshi.adapter(String.class, Collections.emptySet(), "name");
  }

  @Override
  public ChildEmpty fromJson(JsonReader reader) throws IOException {
    ChildEmpty instance = new ChildEmpty();
    reader.beginObject();
    while (reader.hasNext()) {
      int index = reader.selectName(OPTIONS);
      switch (index) {
        case -1:
          reader.skipName();
          reader.skipValue();
          break;
        case 0:
          ((ParentString)instance).name = adapter_name.fromJson(reader);
          break;
      }
    }
    reader.endObject();
    return instance;
  }

  @Override
  public void toJson(JsonWriter writer, ChildEmpty value) throws IOException {
    writer.beginObject();
    writer.name("name");
    adapter_name.toJson(writer, ((ParentString)value).name);
    writer.endObject();
  }
}
