// Code generated by moshi-java-codegen. Do not edit.
package com.github.nename0.moshi.java.codegen.model.simple;

import com.squareup.moshi.JsonAdapter;
import com.squareup.moshi.JsonReader;
import com.squareup.moshi.JsonWriter;
import com.squareup.moshi.Moshi;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Collections;

@SuppressWarnings("unused")
public final class GenericChildNoParamJsonAdapter extends JsonAdapter<GenericChildNoParam> {
  private static final JsonReader.Options OPTIONS = JsonReader.Options.of("generic");

  private final JsonAdapter<String> adapter_generic;

  public GenericChildNoParamJsonAdapter(Moshi moshi) {
    adapter_generic = moshi.adapter(String.class, Collections.emptySet(), "generic");
  }

  @Override
  public GenericChildNoParam fromJson(JsonReader reader) throws IOException {
    GenericChildNoParam instance = new GenericChildNoParam();
    reader.beginObject();
    while (reader.hasNext()) {
      int index = reader.selectName(OPTIONS);
      switch (index) {
        case -1:
          reader.skipName();
          reader.skipValue();
          break;
        case 0:
          ((GenericField<String>)instance).generic = adapter_generic.fromJson(reader);
          break;
      }
    }
    reader.endObject();
    return instance;
  }

  @Override
  public void toJson(JsonWriter writer, GenericChildNoParam value) throws IOException {
    writer.beginObject();
    writer.name("generic");
    adapter_generic.toJson(writer, ((GenericField<String>)value).generic);
    writer.endObject();
  }
}
