// Code generated by moshi-java-codegen. Do not edit.
package com.github.nename0.moshi.java.codegen.model.simple;

import com.squareup.moshi.JsonAdapter;
import com.squareup.moshi.JsonReader;
import com.squareup.moshi.JsonWriter;
import com.squareup.moshi.Moshi;
import com.squareup.moshi.Types;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Override;
import java.lang.SuppressWarnings;
import java.lang.annotation.Annotation;
import java.util.Set;

@SuppressWarnings("unused")
public final class JsonQualifierFieldJsonAdapter extends JsonAdapter<JsonQualifierField> {
  private static final JsonReader.Options OPTIONS = JsonReader.Options.of("color");

  private static final Set<? extends Annotation> ANNOTATIONS_COLOR_0 = Types.getFieldJsonQualifierAnnotations(JsonQualifierField.class, "color");

  private final JsonAdapter<Integer> adapter_color;

  public JsonQualifierFieldJsonAdapter(Moshi moshi) {
    adapter_color = moshi.adapter(int.class, ANNOTATIONS_COLOR_0, "color");
  }

  @Override
  public JsonQualifierField fromJson(JsonReader reader) throws IOException {
    JsonQualifierField instance = new JsonQualifierField();
    reader.beginObject();
    while (reader.hasNext()) {
      int index = reader.selectName(OPTIONS);
      switch (index) {
        case -1:
          reader.skipName();
          reader.skipValue();
          break;
        case 0:
          ((JsonQualifierField)instance).color = adapter_color.fromJson(reader);
          break;
      }
    }
    reader.endObject();
    return instance;
  }

  @Override
  public void toJson(JsonWriter writer, JsonQualifierField value) throws IOException {
    writer.beginObject();
    writer.name("color");
    adapter_color.toJson(writer, ((JsonQualifierField)value).color);
    writer.endObject();
  }
}
